name: 'kubectl-deploy'
description: 'Deploy to k8s with GitHub Action'
inputs:
  restart:
    description: 'The deployment to restart'
    required: true
  namespace:
    description: 'The namespace containing the deployment'
    required: false
    default: 'default'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.restart }}
    - ${{ inputs.namespace }}
