name: 'kubectl-deploy'
description: 'Deploy to k8s with GitHub Action'
inputs:
  deployment:
    description: 'The deployment name to replace the image'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deployment }}
